### ISSUE TITLE
Building image for allien architecture

### ISSUE THREAD

**Issue by matwey** [SUSE/dice#8]
Hello,

Is it possible to use dice to build an image for armv7l on x86_64? If not, please consider this as feature-request.

**Comment by schaefi** [comment]
given that you can provide dice a build worker of the desired architecture, it can do that for you.

dice is just a light weight build system. Currently it supports the following build backends:

* docker
  a docker container from dockerhub is used to run the build. dockers shares the host system kernel.
  I have no information if you can run a cross-arch container. If this is possible it might have its
  limitations

* vagrant
  dice uses vagrant to provision a build worker according to a customized vagrant configuration.
  This allows to run any worker vagrant  supports. You can create an arm VM and run that with
  vagrant plus e.g virtualbox on your x86_64 machine. However I don't know about the performance

* host
  dice just runs the kiwi command on the given host. If you have an arm buildhost accessable via ssh
  somewhere you can point your build to it

For the future I had planned to support public cloud instances as a build host, which means dice starts an instance in e.g ec2 and builds there. If the cloud supports different instance architectures we will benefit from that too

**Comment by matwey** [comment]
Couldn't it use qemu binary translator to run armv7 on x86_64?

**Comment by schaefi** [comment]
from my experience qemu-binfmt by default was very very slow, slower than running qemu-arm or qemu-aarch64 as virtual machine. We needed several performance tweaks to the binfmt setup in order to build packages for arm on x86_64 before we switched to real hardware. I think it's a pretty time consuming task to optimize binfmt for arm image builds on x86_64.

I think if you just take the latest release of a raspberryPI put some prebuild suse image on it and use that as a worker for dice you will be much faster in setup and build time and you will have less trouble
with missing ioctl's and opcodes from arm

just my2cents
